PREDICTIVE MAINTENANCE OF INDUSTRIAL EQUIPMENT

IMPORTING PACKAGES

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

DATASET

In [3]:
data = pd.read_csv('Predictive maintenance.csv')
df = pd.DataFrame(data)
df

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0         1     M14860    M                298.1                    308.6   
1         2     L47181    L                298.2                    308.7   
2         3     L47182    L                298.1                    308.5   
3         4     L47183    L                298.2                    308.6   
4         5     L47184    L                298.2                    308.7   
...     ...        ...  ...                  ...                      ...   
9995   9996     M24855    M                298.8                    308.4   
9996   9997     H39410    H                298.9                    308.4   
9997   9998     M24857    M                299.0                    308.6   
9998   9999     H39412    H                299.0                    308.7   
9999  10000     M24859    M                299.0                    308.7   

      Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  \
0                       1551         42.8                0                0   
1                       1408         46.3                3                0   
2                       1498         49.4                5                0   
3                       1433         39.5                7                0   
4                       1408         40.0                9                0   
...                      ...          ...              ...              ...   
9995                    1604         29.5               14                0   
9996                    1632         31.8               17                0   
9997                    1645         33.4               22                0   
9998                    1408         48.5               25                0   
9999                    1500         40.2               30                0   

      TWF  HDF  PWF  OSF  RNF  
0       0    0    0    0    0  
1       0    0    0    0    0  
2       0    0    0    0    0  
3       0    0    0    0    0  
4       0    0    0    0    0  
...   ...  ...  ...  ...  ...  
9995    0    0    0    0    0  
9996    0    0    0    0    0  
9997    0    0    0    0    0  
9998    0    0    0    0    0  
9999    0    0    0    0    0  

[10000 rows x 14 columns]

In [4]:
df.head()

UDI Product ID Type  Air temperature [K]  Process temperature [K]  \
0    1     M14860    M                298.1                    308.6   
1    2     L47181    L                298.2                    308.7   
2    3     L47182    L                298.1                    308.5   
3    4     L47183    L                298.2                    308.6   
4    5     L47184    L                298.2                    308.7   

   Rotational speed [rpm]  Torque [Nm]  Tool wear [min]  Machine failure  TWF  \
0                    1551         42.8                0                0    0   
1                    1408         46.3                3                0    0   
2                    1498         49.4                5                0    0   
3                    1433         39.5                7                0    0   
4                    1408         40.0                9                0    0   

   HDF  PWF  OSF  RNF  
0    0    0    0    0  
1    0    0    0    0  
2    0    0    0    0  
3    0    0    0    0  
4    0    0    0    0

CHECKING MISSING VALUES

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   UDI                      10000 non-null  int64  
 1   Product ID               10000 non-null  object 
 2   Type                     10000 non-null  object 
 3   Air temperature [K]      10000 non-null  float64
 4   Process temperature [K]  10000 non-null  float64
 5   Rotational speed [rpm]   10000 non-null  int64  
 6   Torque [Nm]              10000 non-null  float64
 7   Tool wear [min]          10000 non-null  int64  
 8   Machine failure          10000 non-null  int64  
 9   TWF                      10000 non-null  int64  
 10  HDF                      10000 non-null  int64  
 11  PWF                      10000 non-null  int64  
 12  OSF                      10000 non-null  int64  
 13  RNF                      10000 non-null  int64  
dtypes: float64(3), int64(9)

In [6]:
df.describe(include='all').T

count unique     top  freq       mean         std  \
UDI                      10000.0    NaN     NaN   NaN     5000.5  2886.89568   
Product ID                 10000  10000  M14860     1        NaN         NaN   
Type                       10000      3       L  6000        NaN         NaN   
Air temperature [K]      10000.0    NaN     NaN   NaN  300.00493    2.000259   
Process temperature [K]  10000.0    NaN     NaN   NaN  310.00556    1.483734   
Rotational speed [rpm]   10000.0    NaN     NaN   NaN  1538.7761  179.284096   
Torque [Nm]              10000.0    NaN     NaN   NaN   39.98691    9.968934   
Tool wear [min]          10000.0    NaN     NaN   NaN    107.951   63.654147   
Machine failure          10000.0    NaN     NaN   NaN     0.0339    0.180981   
TWF                      10000.0    NaN     NaN   NaN     0.0046    0.067671   
HDF                      10000.0    NaN     NaN   NaN     0.0115    0.106625   
PWF                      10000.0    NaN     NaN   NaN     0.0095    0.097009   
OSF                      10000.0    NaN     NaN   NaN     0.0098    0.098514   
RNF                      10000.0    NaN     NaN   NaN     0.0019     0.04355   

                            min      25%     50%      75%      max  
UDI                         1.0  2500.75  5000.5  7500.25  10000.0  
Product ID                  NaN      NaN     NaN      NaN      NaN  
Type                        NaN      NaN     NaN      NaN      NaN  
Air temperature [K]       295.3    298.3   300.1    301.5    304.5  
Process temperature [K]   305.7    308.8   310.1    311.1    313.8  
Rotational speed [rpm]   1168.0   1423.0  1503.0   1612.0   2886.0  
Torque [Nm]                 3.8     33.2    40.1     46.8     76.6  
Tool wear [min]             0.0     53.0   108.0    162.0    253.0  
Machine failure             0.0      0.0     0.0      0.0      1.0  
TWF                         0.0      0.0     0.0      0.0      1.0  
HDF                         0.0      0.0     0.0      0.0      1.0  
PWF                         0.0      0.0     0.0      0.0      1.0  
OSF                         0.0      0.0     0.0      0.0      1.0  
RNF                         0.0      0.0     0.0      0.0      1.0

CHECKING FOR MISSING VALUES HIDDEN AS QUESTION MARK

In [7]:
df.replace("?",np.nan,inplace=True)

CONVERTING TO FLOAT TO MAKE PREPROCESSING EASIER

In [8]:
for column in df.columns:
    try:
        df[column]=df[column].astype(float)
    except:
        pass

DROPING UNIMPORTANT FEATURES

In [9]:
df.drop(['UDI','Product ID'],axis=1,inplace=True)

INCORPORATING FAILURE MODES INTO SINGLE FEATURE

DERIVED FEATURES

In [12]:
df['Power']=df['Rotational speed [rpm]']*df['Torque [Nm]']
df['Power wear']=df['Power']*df['Tool wear [min]']
df['Temperature difference'] = df['Process temperature [K]']-df['Air temperature [K]']
df['Temperature power'] = df['Temperature difference']/df['Power']
df = df[['Air temperature [K]',
         'Process temperature [K]',
         'Rotational speed [rpm]',
         'Torque [Nm]',
         'Tool wear [min]',
         'Power',
         'Power wear',
         'Temperature difference',
         'Temperature power',
         'Type',
         'Machine failure'
        ]]

In [13]:
list(df)

['Air temperature [K]',
 'Process temperature [K]',
 'Rotational speed [rpm]',
 'Torque [Nm]',
 'Tool wear [min]',
 'Power',
 'Power wear',
 'Temperature difference',
 'Temperature power',
 'Type',
 'Machine failure']

CONVERTING CATEGORICAL INFORMATION INTO NUMERIC

In [14]:
df = pd.get_dummies(df,drop_first=True)

In [15]:
df.head()

Air temperature [K]  Process temperature [K]  Rotational speed [rpm]  \
0                298.1                    308.6                  1551.0   
1                298.2                    308.7                  1408.0   
2                298.1                    308.5                  1498.0   
3                298.2                    308.6                  1433.0   
4                298.2                    308.7                  1408.0   

   Torque [Nm]  Tool wear [min]    Power  Power wear  Temperature difference  \
0         42.8              0.0  66382.8         0.0                    10.5   
1         46.3              3.0  65190.4    195571.2                    10.5   
2         49.4              5.0  74001.2    370006.0                    10.4   
3         39.5              7.0  56603.5    396224.5                    10.4   
4         40.0              9.0  56320.0    506880.0                    10.5   

   Temperature power  Machine failure  Type_L  Type_M  
0           0.000158                0       0       1  
1           0.000161                0       1       0  
2           0.000141                0       1       0  
3           0.000184                0       1       0  
4           0.000186                0       1       0

In [16]:
df = df[['Air temperature [K]',
         'Process temperature [K]',
         'Rotational speed [rpm]',
         'Torque [Nm]',
         'Tool wear [min]',
         'Power',
         'Power wear',
         'Temperature difference',
         'Temperature power',
         'Type_L',
         'Type_M',
         'Machine failure'
        ]]

PREPROCESSING

In [22]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import make_pipeline

from sklearn.preprocessing import PowerTransformer

# Scale
pipe = make_pipeline(PowerTransformer())
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
X = pipe.fit_transform(X.copy())



In [23]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [24]:
X.head()
feature_names = list(X.columns)
np.shape(X)

(10000, 11)

In [25]:
len(feature_names)

11

SPLITTING TRAINING AND TESTING DATA

In [26]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size = 0.2, 
                                                    random_state = 0,
                                                    stratify=y)

In [27]:
from sklearn.preprocessing import MinMaxScaler
sc = MinMaxScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

IMPORTING REQUIRED PACKAGES

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
import tensorflow as tf
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

TRAINING AND MODEL EVALUATION

LOGISTIC REGRESSION

KNN

In [51]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)
accuracy_knn = accuracy_score(y_test, y_pred_knn)
precision_knn = precision_score(y_test, y_pred_knn,average='micro')
recall_knn = recall_score(y_test, y_pred_knn,average='micro')
f1_knn = f1_score(y_test, y_pred_knn,average='micro')
cm_knn = confusion_matrix(y_test, y_pred_knn)
print("KNN:")
print(f"Accuracy: {accuracy_knn:.3f}")
print(f"Precision: {precision_knn:.3f}")
print(f"Recall: {recall_knn:.3f}")
print(f"F1-score: {f1_knn:.3f}")
print(f"Confusion matrix:\n{cm_knn}\n")

KNN:
Accuracy: 0.971
Precision: 0.971
Recall: 0.971
F1-score: 0.971
Confusion matrix:
[[1924    0    3    1    2    0]
 [   8    0    0    0    0    0]
 [  17    0    4    0    0    0]
 [  15    0    1    1    0    0]
 [   7    0    0    0   13    0]
 [   4    0    0    0    0    0]]



DECISION TREE

In [44]:
# Train and evaluate decision tree
dt = DecisionTreeClassifier(random_state=0)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)
accuracy_dt = accuracy_score(y_test, y_pred_dt)
precision_dt = precision_score(y_test, y_pred_dt,average='micro')
recall_dt = recall_score(y_test, y_pred_dt,average='micro')
f1_dt = f1_score(y_test, y_pred_dt,average='micro')
cm_dt = confusion_matrix(y_test, y_pred_dt)
print("Decision Tree:")
print(f"Accuracy: {accuracy_dt:.3f}")
print(f"Precision: {precision_dt:.3f}")
print(f"Recall: {recall_dt:.3f}")
print(f"F1-score: {f1_dt:.3f}")
print(f"Confusion matrix:\n{cm_dt}\n")

Decision Tree:
Accuracy: 0.989
Precision: 0.989
Recall: 0.989
F1-score: 0.989
Confusion matrix:
[[1921    3    1    0    0    5]
 [   8    0    0    0    0    0]
 [   0    0   20    0    1    0]
 [   0    0    0   16    1    0]
 [   0    0    0    0   20    0]
 [   3    0    0    0    0    1]]



RANDOM FOREST

In [47]:
# Train and evaluate random forest
rf = RandomForestClassifier(random_state=0)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
precision_rf = precision_score(y_test, y_pred_rf,average='micro')
recall_rf = recall_score(y_test, y_pred_rf,average='micro')
f1_rf = f1_score(y_test, y_pred_rf,average='micro')
cm_rf = confusion_matrix(y_test, y_pred_rf)
print("Random Forest:")
print(f"Accuracy: {accuracy_rf:.3f}")
print(f"Precision: {precision_dt:.3f}")
print(f"Recall: {recall_dt:.3f}")
print(f"F1-score: {f1_dt:.3f}")
print(f"Confusion matrix:\n{cm_dt}\n")


Random Forest:
Accuracy: 0.994
Precision: 0.989
Recall: 0.989
F1-score: 0.989
Confusion matrix:
[[1921    3    1    0    0    5]
 [   8    0    0    0    0    0]
 [   0    0   20    0    1    0]
 [   0    0    0   16    1    0]
 [   0    0    0    0   20    0]
 [   3    0    0    0    0    1]]



GRADIENT BOOSTING

In [49]:
gbc = GradientBoostingClassifier()
gbc.fit(X_train, y_train)
y_pred_gbc = gbc.predict(X_test)
accuracy_gbc = accuracy_score(y_test, y_pred_gbc)
precision_gbc = precision_score(y_test, y_pred_gbc,average='micro')
recall_gbc = recall_score(y_test, y_pred_gbc,average='micro')
f1_gbc = f1_score(y_test, y_pred_gbc,average='micro')
cm_gbc = confusion_matrix(y_test, y_pred_gbc)
print("Gradient Boosting Classifier:")
print(f"Accuracy: {accuracy_gbc:.3f}")
print(f"Precision: {precision_gbc:.3f}")
print(f"Recall: {recall_gbc:.3f}")
print(f"F1-score: {f1_gbc:.3f}")
print(f"Confusion matrix:\n{cm_gbc}\n")

Gradient Boosting Classifier:
Accuracy: 0.992
Precision: 0.992
Recall: 0.992
F1-score: 0.992
Confusion matrix:
[[1925    2    0    0    0    3]
 [   8    0    0    0    0    0]
 [   0    0   21    0    0    0]
 [   0    0    0   17    0    0]
 [   0    0    0    0   20    0]
 [   4    0    0    0    0    0]]



SVM

In [50]:
svm = SVC()
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)
accuracy_svm = accuracy_score(y_test, y_pred_svm)
precision_svm = precision_score(y_test, y_pred_svm,average='micro')
recall_svm = recall_score(y_test, y_pred_svm,average='micro')
f1_svm = f1_score(y_test, y_pred_svm,average='micro')
cm_svm = confusion_matrix(y_test, y_pred_svm)
print("Support Vector Machine Classifier:")
print(f"Accuracy: {accuracy_svm:.3f}")
print(f"Precision: {precision_svm:.3f}")
print(f"Recall: {recall_svm:.3f}")
print(f"F1-score: {f1_svm:.3f}")
print(f"Confusion matrix:\n{cm_svm}\n")

Support Vector Machine Classifier:
Accuracy: 0.973
Precision: 0.973
Recall: 0.973
F1-score: 0.973
Confusion matrix:
[[1930    0    0    0    0    0]
 [   8    0    0    0    0    0]
 [  21    0    0    0    0    0]
 [  16    0    0    1    0    0]
 [   6    0    0    0   14    0]
 [   4    0    0    0    0    0]]

